import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Dashboard from '@/components/Dashboard'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Peliculas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Dashboard></Dashboard>
        {children}</body>
    </html>
  )
}
